### ISSUE TITLE
Fix import identified issues

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-theblog-importer#12]
2 types of issues.

**Pure import process issues**
Errors resulting of import edge cases.

- [x] blob storage image copy fails if image is being a redirect (`x-ms-copy-source` does not support redirect)
- [ ] some images have weird / unsupported urls. Need to examine case by case

**Unsupported md data structure

- [ ] `<figure>` tag transformed to `code` block: https://theblog--adobe.hlx.page/en/drafts/migrated/2020/04/01/get-to-great-faster.html
- [x] transform to embeds for list of supported embeds - see https://github.com/adobe/theblog/issues/166
  - [x] youtube: https://theblog.adobe.com/so-how-are-you-feeling/ -> https://theblog-adobe.hlx.page/en/drafts/migrated/2020/04/13/so-how-are-you-feeling.html
  - [x] soundcloud: https://theblog.adobe.com/building-a-better-onboarding-experience/ -> https://theblog-adobe.hlx.page/en/drafts/migrated/2020/02/13/building-a-better-onboarding-experience.html
  - [x] slideshare: https://theblog.adobe.com/5-takeaways-from-this-months-digital-price-index/ -> https://theblog-adobe.hlx.page/en/drafts/migrated/2019/04/24/5-takeaways-from-this-months-digital-price-index.html
- [x] transform banners - see https://github.com/adobe/theblog/issues/162

Non exhaustive list - WIP/

**Comment by rofe** [comment]
- [ ] detect _main_ topic (look for `<meta property="article:section" content="...">`) and add it as the 1st topic
- [ ] images with captions (typically wrapped in `<figure>`): currently the caption is just normal text below the image, but we should be able to give it a dedicated style
- [ ] turn youtube videos, slideshows etc into proper `helix-embed` links, e.g. [original](https://theblog.adobe.com/so-how-are-you-feeling/) vs [import](https://theblog-adobe.hlx.page/en/archive/2020/so-how-are-you-feeling.html)
- [ ] turn promotional/product  banners (look for `div.product-banner-wrap`) into `helix-embed` links, requires https://github.com/adobe/theblog/issues/162

**Comment by kptdobe** [comment]
> images with captions (typically wrapped in <figure>): currently the caption is just normal text below the image, but we should be able to give it a dedicated style
> <figure> tag transformed to code block: https://theblog--adobe.hlx.page/en/drafts/migrated/2020/04/01/get-to-great-faster.html

I think the problem for https://theblog.adobe.com/get-to-great-faster is not the `<figure>`. It is just a silly markdown: 

```
<ul>
  <li>
    <strong>Organized &amp; Efficient <b><span lang="EN-US">with Productions</span></b>, So You Can Get to Great Faster
      <br>
     </strong><a href="https://youtu.be/YFMm2arr8GA" target="_blank" rel="noopener">Watch the recording</a>.
    <em>
      <br>
    </em>
    <p></p>
    <figure id="attachment_88983" style="width: 300px" class="wp-caption alignright"><img 
      class="size-full wp-image-88983 article-image image-media-img"                         
      src="https://theblogimages.adobe.com/wp-content/uploads/2020/04/Untitled-11.jpg" alt=""       
      width="300" height="148" draggable="false"><figcaption class="wp-caption-text">Jason 
      Levine &amp; Karl Soule</figcaption></figure>
    <p></p>
  </li>
</ul>
```

`<br>` in strong tag, multiple `<p>` and `<br>` tag in a list item... not clue how the browser manages to render this properly ;)
The transformation to md respects the input, it is just that this then has no meaning.

After final import, we'll have to fix this one manually.

**Comment by kptdobe** [comment]
> images with captions (typically wrapped in `<figure>`): currently the caption is just normal text below the image, but we should be able to give it a dedicated style

@rofe Yes but how do you describe this in markdown ?

**Comment by kptdobe** [comment]
> preserve alt text of hero image for metadata

What do you mean ? I randomly checked some blog entries, none of the hero image has an alt text. 
I could have the page title but this would be useless for metadata.

**Comment by rofe** [comment]
> Yes but how do you describe this in markdown ?

🤷‍♂️ 😂 

>  I randomly checked some blog entries, none of the hero image has an alt text.

I ran into an article which had one the other day, can't remember which one though... I guess we should just be prepared to migrate the alt text IF it's there...

**Comment by rofe** [comment]
...and img title while we're at it: `![alt text](url "title")`
If they're empty, they're empty.

**Comment by kptdobe** [comment]
Weird, this should work. Maybe I lose them during the blobstorage link rewrite. I check (and fix).

**Comment by rofe** [comment]
If it is already working, then even better :) I just wanted to make suire we think of it, as it is also related to SEO metadata.

**Comment by kptdobe** [comment]
I could not find an example for the `title` but works fine for the `alt`: see https://theblog-adobe.hlx.page/en/drafts/migrated/2015/03/12/mobile-reality.html images in content have an alt as in source doc.

**Comment by rofe** [comment]
OK, great. Interestingly, in this particular example, they all link to an original size image on `blogs.adobe.com`...

I assume the alt & title text preservation mechanism would work identically for the hero image, right?

**Comment by kptdobe** [comment]
> OK, great. Interestingly, in this particular example, they all link to an original size image on blogs.adobe.com...

Yes, I only update the img src with the blobstorage link. I should enhance the regex to cover this case too.

> I assume the alt & title text preservation mechanism would work identically for the hero image, right?
Yes but I could not find a single one with a title/alt...

**Comment by kptdobe** [comment]
Closing this container. Open individual issues for remaining unsupported cases.
